#define Systemrequirements 4
#define SelectingItems 27
#define Resizing 13
#define Rotating 28
#define ChangingtheLayers 30
#define Croppingyourphoto 10
#define Changingthecolourofyourshape 12
#define GettingStarted 0
#define Addtext 1
#define Addashape 2
#define AddImage 3
#define OpenaYearbook 5
#define FinishingyourYearbook 6
#define Printing 7
#define PublishingforInternet 8
#define Saving 9
#define Addingtextformating 11
#define BoldItalicorUnderline 23
#define Color 24
#define Font 25
#define FontSize 29
#define Advanced 26
#define Navigation 14
#define AddPage 18
#define DeletePage 19
#define QuickChanging 20
#define ChangingtheZoom 15
